/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

import controller.ProjectController;
import java.util.List;
import model.Project;


public class App {
    

    public static void main(String[] args) {

        ProjectController projectController = new ProjectController();

        Project project = new Project();
        project.setId(3);
        project.setName("Projeto NOVO teste");
        project.setDescription("description DA PORRA");
        
   //     projectController.save(project);
        
        projectController.update(project);

        List<Project> projects = projectController.getAll();
        System.out.println("Total de projetos = " + projects.size());
        
        projectController.removeById(4);
    }

}
